apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::072542201448:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-HGUSN0VGQUTA
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::072542201448:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-30T22:38:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1778"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 3358e1fe-1b92-471d-a94a-a2e9fadadc46
