apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::072542201448:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1TV0AGLCNFBVC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::072542201448:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-29T09:10:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8203"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: eee92767-9145-4674-a19b-80dae1bc86ed
